# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:5.5
    container_name: se3mysql
#    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PdTza455
      MYSQL_USER: se3db_admin
      MYSQL_PASSWORD: KorTeX50
#      MYSQL_DATABASE: se3db
    networks:
      default:
        ipv4_address: 172.22.0.2

  adminer:
    image: adminer
    container_name: se3adminer
    restart: always
    ports:
      - 8080:8080 
networks:
    default:
      external:
        name: se3network
