version: '3'

services:
  calibre-web-app:
     container_name: calibre-web
     image: linuxserver/calibre-web:latest
     restart: unless-stopped
     user: "33:33"
     volumes:
        - /home/nextcloud/cloud/data/nicolas/files/Documents/Bibliothèque calibre/:/books
        - /home/calibre/config:/config
     ports:
        - "37.59.44.88:8083:443"
     environment:
        VIRTUAL_HOST: ppsx.be
        USER: nicolas
        #PASSWORD: qmrXT86
        HTTP_PASSWORD: qmrXT86
        LETSENCRYPT_HOST: ppsx.be
        LETSENCRYPT_EMAIL: nroudninski@protonmail.com

networks:
    default:
       external:
         name: webproxy
